name: build-and-deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 12.13.0
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - run: yarn install

    - run: yarn build-azure

    # Building is done. Now reinstall only those packages needed to actually run the application.

    - run: rm -rf node_modules

    - run: yarn install --production

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dothemath-app-api'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3051375fa3a44466aa191d36d89a4b9e }}
        package: .
