name: build-and-deploy-to-test

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy-to-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 14.16.1
      uses: actions/setup-node@v1
      with:
        node-version: '14.16.1'

    - run: yarn install

    - run: yarn build:azure

    # Building is done. Now reinstall only those packages needed to actually run the application.

    - run: rm -rf node_modules

    - run: yarn install --production

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dothemath-app-api-test'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b9ceaeaa6a0f490d9126fe1844e1b441 }}
        package: .
