name: build

on:
  push:
    branches-ignore:
      - master
      - test

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 14.16.1
      uses: actions/setup-node@v1
      with:
        node-version: '14.16.1'

    - run: yarn install

    - run: yarn build-azure

    # Building is done. Now reinstall only those packages needed to actually run the application.
    # We only do this here for parity with the build-and-deploy script.

    - run: rm -rf node_modules

    - run: yarn install --production
