name: build

on:
  push:
    branches-ignore:
      - main
      - test

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: "18.12.1"

      - run: yarn install

      - run: yarn ts-coverage

      - run: yarn build:azure

      # Building is done. Now reinstall only those packages needed to actually run the application.
      # We only do this here for parity with the build-and-deploy script.

      - run: rm -rf node_modules

      - run: yarn install --production
